num_bases: 4
emb_dim: 768
num_layers: 6
dropout: 0.0
JK: "last"
lr: 0.0001
l2: 0
num_epochs: 3
batch_size: 16
num_workers: 0
seed: 1
data_path:
offline_log: True
exp_name: ""
train_sample_size: -1
eval_sample_size: -1
rwpe:
task_names:
 - my_data_lev_l2lev_n
#task_names:
#  - mydata
llm_name: "llama2_13b"
llm_b_size: 100
load_texts: False
max_nodes_per_hop: 100
load_best: False
test_rep: 1
val_interval: 1
model_dir: "OneForAll/cache_data/my_data_lev_l2lev_n/llama2_13b/graph_model/best.ckpt"
output_file: "relation_predictions.txt"